basePath: /v1
definitions:
  controllers.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  models.RoleForAdd:
    properties:
      description:
        type: string
      roleName:
        type: string
    type: object
  models.UserForAdd:
    properties:
      email:
        type: string
      mobile:
        type: string
      password:
        type: string
      roleID:
        type: integer
      username:
        type: string
    type: object
  models.UserForUpdate:
    properties:
      email:
        type: string
      mobile:
        type: string
      roleID:
        type: integer
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: 电子物证
  version: "1.0"
paths:
  /image/classify:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 输入一张图片，输出图片中的多个通用物体和场景, 给图片分类
      parameters:
      - description: 图片的base64编码,去掉编码头,图片大小不超过4M
        in: formData
        name: image
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 图像分类，识别通用物体
      tags:
      - image 图像
  /image/face/detect:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 获取人脸的位置, 人脸相关的属性，如 性别，年龄等，人脸的质量信息，相关因素如亮度，遮挡，模糊，完整度， 置信度等；人脸关键点信息等
      parameters:
      - description: 图片的base64编码,去掉编码头
        in: formData
        name: image
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 人脸检测
      tags:
      - image 图像
  /role:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 获取所有角色
      tags:
      - role 角色
    post:
      consumes:
      - application/json
      parameters:
      - description: role json
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.RoleForAdd'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 添加角色
      tags:
      - role 角色
  /role/{id}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: role id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 删除角色
      tags:
      - role 角色
    get:
      parameters:
      - description: 角色 id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 获取单个角色
      tags:
      - role 角色
    put:
      consumes:
      - application/json
      parameters:
      - description: role json
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.RoleForAdd'
          type: object
      - description: role id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 编辑角色
      tags:
      - role 角色
  /user:
    get:
      consumes:
      - application/json
      parameters:
      - description: now page
        in: query
        name: nowPage
        type: integer
      - description: page size
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 获取用户
      tags:
      - user 用户
    post:
      consumes:
      - application/json
      parameters:
      - description: user for add
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.UserForAdd'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 添加用户
      tags:
      - user 用户
  /user/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 删除单个用户
      tags:
      - user 用户
    get:
      consumes:
      - application/json
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 获取单个用户
      tags:
      - user 用户
    put:
      consumes:
      - application/json
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      - description: user for update
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.UserForUpdate'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 更新用户
      tags:
      - user 用户
  /user/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: user name
        in: formData
        name: Username
        required: true
        type: string
      - description: user password
        in: formData
        name: Password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      summary: 用户登录
      tags:
      - user 用户
  /user/logout:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: refresh token
        in: formData
        name: RefreshToken
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 用户退出, 销毁token 和 refreshToken
      tags:
      - user 用户
  /user/refreshToken:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: refresh token
        in: formData
        name: RefreshToken
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      security:
      - ApiKeyAuth: []
      summary: 用户获取新的token,新旧token会同时生效,旧的token 1分钟之后被销毁
      tags:
      - user 用户
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
