basePath: /v1
definitions:
  controllers.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  models.RoleForAdd:
    properties:
      description:
        type: string
      roleName:
        type: string
    type: object
  models.UserForAdd:
    properties:
      email:
        type: string
      mobile:
        type: string
      password:
        type: string
      roleID:
        type: integer
      username:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: 电子物证
  version: "1.0"
paths:
  /role:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      summary: 获取所有角色
      tags:
      - role
    post:
      consumes:
      - application/json
      parameters:
      - description: role json
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.RoleForAdd'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      summary: 添加角色
      tags:
      - role
    put:
      consumes:
      - application/json
      parameters:
      - description: role json
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.RoleForAdd'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      summary: 编辑角色
      tags:
      - role
  /role/{id}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: role id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      summary: 删除角色
      tags:
      - role
    get:
      parameters:
      - description: 角色 id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      summary: 获取单个角色
      tags:
      - role
  /users:
    get:
      consumes:
      - application/json
      parameters:
      - description: now page
        in: query
        name: nowPage
        type: integer
      - description: page size
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      summary: 获取用户
      tags:
      - user
    post:
      consumes:
      - application/json
      parameters:
      - description: user for add
        in: body
        name: body
        schema:
          $ref: '#/definitions/models.UserForAdd'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Response'
            type: object
      summary: 添加用户
      tags:
      - user
swagger: "2.0"
